import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { User } from './models/User';
import { FoodItem } from './models/FoodItem';
import { Coupon } from './models/Coupon';
import { Order } from './models/Order';

dotenv.config();

const seedData = async () => {
  try {
    // Connect to database
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/foodie_haven');
    console.log('✅ MongoDB Connected');

    // Clear existing data
    await User.deleteMany({});
    await FoodItem.deleteMany({});
    await Coupon.deleteMany({});
    await Order.deleteMany({});
    console.log('🗑️  Cleared existing data');

    // Create admin user
    const admin = await User.create({
      fullName: 'Admin User',
      email: 'admin@foodiehaven.com',
      password: 'admin123',
      phone: '+91 98765 00000',
      role: 'admin',
    });
    console.log('👤 Admin user created');

    // Create demo customer
    const customer = await User.create({
      fullName: 'Rahul Sharma',
      email: 'demo@example.com',
      password: 'demo123',
      phone: '+91 98765 43210',
      role: 'customer',
    });
    console.log('👤 Demo customer created');

    // Create food items
    const foodItems = [
      {
        name: 'Classic Chicken Cheese Burger',
        description: 'Juicy grilled chicken patty topped with melted cheese, crisp lettuce, farm-fresh tomatoes, and desi tandoori mayo in a toasted sesame bun',
        price: 299,
        originalPrice: 399,
        category: 'Burgers',
        image: '/images/chicken_cheese_burger.jpg',
        isVeg: false,
        rating: 4.8,
        ratingCount: 328,
        isAvailable: true,
        isPopular: true,
        prepTimeMinutes: 15,
        calories: 620,
        ingredients: ['Chicken patty', 'Cheddar cheese', 'Lettuce', 'Tomato', 'Onions', 'Tandoori mayo', 'Sesame bun'],
      },
      {
        name: 'Spicy Chicken Burger',
        description: 'Crispy fried golden chicken fillet infused with spicy Indian masala rub, fresh green chillies, zesty garlic dip, and crisp iceberg lettuce',
        price: 279,
        category: 'Burgers',
        image: '/images/spicy_chicken_burger.jpg',
        isVeg: false,
        rating: 4.6,
        ratingCount: 412,
        isAvailable: true,
        isPopular: true,
        prepTimeMinutes: 18,
        calories: 580,
        ingredients: ['Crispy spiced chicken', 'Chilli garlic sauce', 'Jalapeños', 'Lettuce', 'Brioche bun'],
      },
      {
        name: 'Veggie Delight Burger',
        description: 'Crispy spiced vegetable and potato patty seasoned with Indian herbs, fresh mint mayonnaise, crunchy onions, and tomatoes on a soft toasted bun',
        price: 249,
        category: 'Burgers',
        image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80',
        isVeg: true,
        rating: 4.5,
        ratingCount: 187,
        isAvailable: true,
        prepTimeMinutes: 12,
        calories: 450,
        ingredients: ['Spiced veggie patty', 'Lettuce', 'Tomato', 'Mint mayo', 'Crispy onions', 'Whole wheat bun'],
      },
      {
        name: 'Margherita Pizza',
        description: 'Handcrafted pizza crust topped with sun-ripened Indian plum tomato sauce, melted mozzarella cheese, fresh basil leaves, and aromatic herbs',
        price: 349,
        category: 'Pizza',
        image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80',
        isVeg: true,
        rating: 4.7,
        ratingCount: 592,
        isAvailable: true,
        isChefSpecial: true,
        prepTimeMinutes: 20,
        calories: 800,
        ingredients: ['Pizza dough', 'Tomato sauce', 'Fresh mozzarella', 'Basil', 'Olive oil'],
      },
      {
        name: 'Tandoori Paneer Tikka Pizza',
        description: 'Loaded with succulent tandoori paneer tikka chunks, melted mozzarella cheese, crunchy capsicum, red onions, and fragrant Indian herbs',
        price: 399,
        originalPrice: 499,
        category: 'Pizza',
        image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&q=80',
        isVeg: true,
        rating: 4.8,
        ratingCount: 745,
        isAvailable: true,
        isPopular: true,
        prepTimeMinutes: 22,
        calories: 880,
        ingredients: ['Pizza dough', 'Tandoori sauce', 'Mozzarella', 'Paneer tikka', 'Capsicum', 'Onions', 'Indian herbs'],
      },
      {
        name: 'Creamy Alfredo Pasta',
        description: 'Fettuccine pasta tossed in rich velvety fresh cream sauce, butter, garlic, crushed black pepper, and grated parmesan cheese',
        price: 329,
        category: 'Pasta',
        image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800&q=80',
        isVeg: true,
        rating: 4.6,
        ratingCount: 421,
        isAvailable: true,
        isChefSpecial: true,
        prepTimeMinutes: 18,
        calories: 720,
        ingredients: ['Fettuccine', 'Heavy cream', 'Parmesan', 'Butter', 'Garlic', 'Black pepper'],
      },
      {
        name: 'Hyderabadi Chicken Biryani',
        description: 'Royal dum-cooked fragrant basmati rice layered with marinated chicken, saffron, fried golden onions (birista), fresh mint, and shahi spices',
        price: 349,
        category: 'Biryani',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
        isVeg: false,
        rating: 4.8,
        ratingCount: 892,
        isAvailable: true,
        isPopular: true,
        isChefSpecial: true,
        prepTimeMinutes: 30,
        calories: 850,
        ingredients: ['Basmati rice', 'Chicken', 'Yogurt', 'Spices', 'Saffron', 'Fried onions', 'Mint'],
      },
      {
        name: 'Paneer Tikka',
        description: 'Tender cubes of fresh cottage cheese marinated in spiced yogurt, tandoori masala, and grilled with capsicum and onions in tandoor',
        price: 209,
        category: 'Starters',
        image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&q=80',
        isVeg: true,
        rating: 4.7,
        ratingCount: 523,
        isAvailable: true,
        isChefSpecial: true,
        prepTimeMinutes: 18,
        calories: 350,
        ingredients: ['Paneer', 'Yogurt', 'Tandoori masala', 'Bell peppers', 'Onions'],
      },
      {
        name: 'Butter Chicken',
        description: 'Tender tandoori chicken simmered in a velvety smooth tomato, cashew, and butter gravy infused with fragrant kasuri methi',
        price: 379,
        category: 'Main Course',
        image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&q=80',
        isVeg: false,
        rating: 4.8,
        ratingCount: 678,
        isAvailable: true,
        isPopular: true,
        isChefSpecial: true,
        prepTimeMinutes: 25,
        calories: 720,
        ingredients: ['Chicken', 'Tomato gravy', 'Butter', 'Cream', 'Spices', 'Kasuri methi'],
      },
      {
        name: 'Dal Makhani',
        description: 'Traditional slow-cooked whole black lentils and kidney beans simmered overnight with tomatoes, fresh cream, and pure desi butter',
        price: 249,
        category: 'Main Course',
        image: '/images/dal_makhani.jpg',
        isVeg: true,
        rating: 4.9,
        ratingCount: 556,
        isAvailable: true,
        isChefSpecial: true,
        prepTimeMinutes: 30,
        calories: 420,
        ingredients: ['Black lentils', 'Kidney beans', 'Tomato puree', 'Desi Butter', 'Fresh Cream', 'Kashmiri spices'],
      },
      {
        name: 'Chocolate Lava Cake',
        description: 'Decadent warm chocolate cake with a molten chocolate fudge center, served warm with vanilla bean ice cream',
        price: 189,
        category: 'Desserts',
        image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&q=80',
        isVeg: true,
        rating: 4.9,
        ratingCount: 723,
        isAvailable: true,
        isPopular: true,
        prepTimeMinutes: 15,
        calories: 520,
        ingredients: ['Dark chocolate', 'Butter', 'Eggs', 'Sugar', 'Flour', 'Vanilla ice cream'],
      },
      {
        name: 'Tiramisu',
        description: 'Classic Italian dessert made with espresso-soaked sponge layers, rich mascarpone cream, and dusted with dark cocoa powder',
        price: 219,
        category: 'Desserts',
        image: '/images/tiramisu.jpg',
        isVeg: true,
        rating: 4.7,
        ratingCount: 512,
        isAvailable: true,
        prepTimeMinutes: 10,
        calories: 450,
        ingredients: ['Ladyfinger biscuits', 'Mascarpone', 'Coffee', 'Cocoa powder', 'Sugar'],
      },
      {
        name: 'Gulab Jamun',
        description: 'Soft and melt-in-the-mouth golden fried milk solid dumplings soaked in aromatic rose, cardamom, and saffron sugar syrup',
        price: 129,
        category: 'Desserts',
        image: '/images/gulab_jamun.jpg',
        isVeg: true,
        rating: 4.9,
        ratingCount: 834,
        isAvailable: true,
        isPopular: true,
        isChefSpecial: true,
        prepTimeMinutes: 8,
        calories: 380,
        ingredients: ['Khoya milk solids', 'Cardamom', 'Rose water', 'Saffron syrup', 'Pistachios'],
      },
      {
        name: 'Veggie Supreme',
        description: 'Loaded with crunchy capsicum, sweet corn, mushrooms, red onions, black olives, and melted mozzarella with desi herb seasoning',
        price: 379,
        category: 'Pizza',
        image: 'https://images.pexels.com/photos/5792329/pexels-photo-5792329.jpeg?auto=compress&cs=tinysrgb&w=800',
        isVeg: true,
        rating: 4.4,
        ratingCount: 289,
        isAvailable: true,
        prepTimeMinutes: 20,
        calories: 750,
        ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Bell peppers', 'Onions', 'Mushrooms', 'Olives', 'Tomatoes'],
      },
      {
        name: 'Spicy Arrabbiata',
        description: 'Penne pasta simmered in fiery tomato sauce infused with red chillies, fragrant garlic, and aromatic Indian-Italian herbs',
        price: 299,
        category: 'Pasta',
        image: 'https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&w=800',
        isVeg: true,
        rating: 4.4,
        ratingCount: 256,
        isAvailable: true,
        prepTimeMinutes: 15,
        calories: 550,
        ingredients: ['Penne', 'Tomato sauce', 'Red chili flakes', 'Garlic', 'Olive oil', 'Basil'],
      },
      {
        name: 'Chicken Pesto Pasta',
        description: 'Tender grilled chicken tossed in fresh basil pesto, cherry tomatoes, olive oil, and melted cheese',
        price: 379,
        category: 'Pasta',
        image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80',
        isVeg: false,
        rating: 4.7,
        ratingCount: 503,
        isAvailable: true,
        isPopular: true,
        prepTimeMinutes: 20,
        calories: 680,
        ingredients: ['Fusilli', 'Grilled chicken', 'Basil pesto', 'Cherry tomatoes', 'Parmesan', 'Pine nuts'],
      },
      {
        name: 'Vegetable Dum Biryani',
        description: 'Aromatic long-grain basmati rice slow-cooked in traditional dum style with fresh garden vegetables, saffron, cashews, and whole spices',
        price: 279,
        category: 'Biryani',
        image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&q=80',
        isVeg: true,
        rating: 4.5,
        ratingCount: 387,
        isAvailable: true,
        prepTimeMinutes: 25,
        calories: 650,
        ingredients: ['Basmati rice', 'Mixed vegetables', 'Yogurt', 'Spices', 'Saffron', 'Mint', 'Cashews'],
      },
      {
        name: 'Mutton Biryani',
        description: 'Tender succulent mutton pieces slow-cooked with aged basmati rice, rich kewra water, saffron, desi ghee, and royal Nawabi spices',
        price: 429,
        category: 'Biryani',
        image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800&q=80',
        isVeg: false,
        rating: 4.9,
        ratingCount: 612,
        isAvailable: true,
        isPopular: true,
        prepTimeMinutes: 35,
        calories: 920,
        ingredients: ['Basmati rice', 'Mutton', 'Yogurt', 'Spices', 'Saffron', 'Fried onions', 'Mint', 'Coriander'],
      },
      {
        name: 'Amritsari Chicken Wings',
        description: 'Crispy golden fried chicken wings tossed in fiery Amritsari spice rub and tangy peri-peri garlic dip',
        price: 229,
        category: 'Starters',
        image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&q=80',
        isVeg: false,
        rating: 4.6,
        ratingCount: 445,
        isAvailable: true,
        isPopular: true,
        prepTimeMinutes: 15,
        calories: 480,
        ingredients: ['Chicken wings', 'Amritsari spices', 'Butter', 'Garlic', 'Chilli dip'],
      },
      {
        name: 'Mozzarella Sticks',
        description: 'Golden crisp fried cheese fingers oozing melted mozzarella, served with tangy spiced tomato salsa dip',
        price: 189,
        category: 'Starters',
        image: 'https://images.pexels.com/photos/5419336/pexels-photo-5419336.jpeg?auto=compress&cs=tinysrgb&w=800',
        isVeg: true,
        rating: 4.5,
        ratingCount: 312,
        isAvailable: true,
        prepTimeMinutes: 10,
        calories: 420,
        ingredients: ['Mozzarella', 'Breadcrumbs', 'Marinara sauce', 'Italian herbs'],
      },
      {
        name: 'Crispy Veg Spring Rolls',
        description: 'Crispy golden pastry sheets stuffed with shredded cabbage, carrots, bell peppers, and spiced noodles with sweet chilli dip',
        price: 159,
        category: 'Starters',
        image: 'https://images.pexels.com/photos/2365946/pexels-photo-2365946.jpeg?auto=compress&cs=tinysrgb&w=800',
        isVeg: true,
        rating: 4.3,
        ratingCount: 198,
        isAvailable: true,
        prepTimeMinutes: 12,
        calories: 280,
        ingredients: ['Spring roll wrappers', 'Cabbage', 'Carrots', 'Bean sprouts', 'Sweet chili sauce'],
      },
      {
        name: 'Paneer Butter Masala',
        description: 'Fresh cottage cheese cubes cooked in a rich, creamy, mildly sweet and spicy tomato-butter gravy with aromatic Indian spices',
        price: 329,
        category: 'Main Course',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
        isVeg: true,
        rating: 4.6,
        ratingCount: 542,
        isAvailable: true,
        prepTimeMinutes: 20,
        calories: 580,
        ingredients: ['Paneer', 'Tomato gravy', 'Butter', 'Cream', 'Spices', 'Kasuri methi'],
      },
      {
        name: 'Tandoori Grilled Fish',
        description: 'Fresh fish fillet delicately marinated in lemon, crushed garlic, ajwain (carom seeds), and Indian spices, grilled to flaky perfection',
        price: 499,
        category: 'Main Course',
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80',
        isVeg: false,
        rating: 4.7,
        ratingCount: 389,
        isAvailable: true,
        prepTimeMinutes: 22,
        calories: 650,
        ingredients: ['Fish fillet', 'Lemon', 'Butter', 'Garlic', 'Ajwain spices', 'Herbs'],
      },
      {
        name: 'Cheesecake',
        description: 'Creamy New York style baked cheesecake on a buttery biscuit base topped with sweet berry compote',
        price: 219,
        category: 'Desserts',
        image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&q=80',
        isVeg: true,
        rating: 4.8,
        ratingCount: 445,
        isAvailable: true,
        prepTimeMinutes: 12,
        calories: 520,
        ingredients: ['Cream cheese', 'Graham crackers', 'Sugar', 'Eggs', 'Berry compote'],
      },
      {
        name: 'Coca Cola',
        description: 'Chilled refreshing classic cola beverage served with ice',
        price: 60,
        category: 'Beverages',
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
        isVeg: true,
        rating: 4.5,
        ratingCount: 892,
        isAvailable: true,
        prepTimeMinutes: 2,
        calories: 140,
        ingredients: ['Carbonated water', 'Sugar', 'Flavors'],
      },
      {
        name: 'Fresh Lime Soda',
        description: 'Refreshing sweet and salty carbonated beverage with fresh squeezed lime juice, mint leaves, and black salt (kala namak)',
        price: 79,
        category: 'Beverages',
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
        isVeg: true,
        rating: 4.6,
        ratingCount: 276,
        isAvailable: true,
        prepTimeMinutes: 5,
        calories: 80,
        ingredients: ['Fresh lime', 'Soda', 'Mint', 'Kala Namak', 'Sugar'],
      },
      {
        name: 'South Indian Iced Coffee',
        description: 'Chilled rich brewed South Indian filter coffee blended with cold milk and crushed ice',
        price: 129,
        category: 'Beverages',
        image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80',
        isVeg: true,
        rating: 4.8,
        ratingCount: 512,
        isAvailable: true,
        prepTimeMinutes: 5,
        calories: 120,
        ingredients: ['Filter Coffee decoction', 'Ice', 'Full cream milk', 'Sugar'],
      },
      {
        name: 'Fresh Mango Lassi',
        description: 'Traditional Punjabi chilled yogurt beverage blended with sweet ripe Alphonso mangoes, garnished with cardamom and pistachios',
        price: 99,
        category: 'Beverages',
        image: '/images/mango_lassi.jpg',
        isVeg: true,
        rating: 4.9,
        ratingCount: 589,
        isAvailable: true,
        isPopular: true,
        isChefSpecial: true,
        prepTimeMinutes: 5,
        calories: 220,
        ingredients: ['Alphonso Mango', 'Fresh Curd / Yogurt', 'Sugar', 'Cardamom', 'Pistachios', 'Saffron'],
      },
    ];

    await FoodItem.insertMany(foodItems);
    console.log(`🍔 ${foodItems.length} food items created`);

    // Create coupons
    const coupons = [
      {
        code: 'WELCOME50',
        discountType: 'percentage',
        discountValue: 50,
        minOrderAmount: 500,
        maxDiscount: 250,
        description: 'Get 50% off on your first order (max ₹250)',
        isActive: true,
      },
      {
        code: 'SAVE15',
        discountType: 'percentage',
        discountValue: 15,
        minOrderAmount: 700,
        description: 'Save 15% on orders above ₹700',
        isActive: true,
      },
      {
        code: 'FLAT100',
        discountType: 'fixed',
        discountValue: 100,
        minOrderAmount: 600,
        description: 'Get ₹100 off on orders above ₹600',
        isActive: true,
      },
      {
        code: 'FREESHIP',
        discountType: 'fixed',
        discountValue: 50,
        minOrderAmount: 800,
        description: 'Free delivery on orders above ₹800',
        isActive: true,
      },
    ];

    await Coupon.insertMany(coupons);
    console.log(`🎟️  ${coupons.length} coupons created`);

    // Create sample orders for demo customer
    const sampleOrders = [
      {
        orderNumber: 'ORD-K9J2L-8F3P',
        userId: customer._id,
        customer: {
          fullName: 'Rahul Sharma',
          email: 'demo@example.com',
          phone: '+91 98765 43210',
        },
        items: [
          {
            id: 'burger-1-default',
            foodItem: { name: 'Classic Chicken Cheese Burger', price: 299, image: '/images/chicken_cheese_burger.jpg' },
            quantity: 2,
            selectedCustomizations: [
              { groupId: 'patty-type', groupTitle: 'Patty Options', optionId: 'single', optionName: 'Single Patty', price: 0 },
            ],
            selectedAddOns: [
              { id: 'extra-cheese', name: 'Extra Cheese', price: 40 },
            ],
            unitPrice: 339,
            totalPrice: 678,
          },
          {
            id: 'beverage-1-default',
            foodItem: { name: 'Fresh Mango Lassi', price: 99, image: '/images/mango_lassi.jpg' },
            quantity: 2,
            selectedCustomizations: [],
            selectedAddOns: [],
            unitPrice: 99,
            totalPrice: 198,
          },
        ],
        subtotal: 876,
        deliveryFee: 0,
        tax: 70,
        discount: 100,
        grandTotal: 846,
        status: 'Out for Delivery',
        deliveryAddress: {
          fullName: 'Rahul Sharma',
          phone: '+91 98765 43210',
          email: 'demo@example.com',
          houseNumber: 'Flat 402, Sunshine Apts',
          street: '12th Main, Indiranagar',
          city: 'Bangalore',
          state: 'Karnataka',
          pincode: '560038',
          instructions: 'Please ring bell twice and leave with security.',
        },
        deliveryType: 'standard',
        paymentMethod: 'upi',
        paymentStatus: 'Paid',
        estimatedDeliveryTime: '25-35 mins',
        statusTimestamps: {
          placed: new Date(Date.now() - 15 * 60 * 1000),
          confirmed: new Date(Date.now() - 12 * 60 * 1000),
          preparing: new Date(Date.now() - 8 * 60 * 1000),
          outForDelivery: new Date(Date.now() - 2 * 60 * 1000),
        },
      },
      {
        orderNumber: 'ORD-M4B7V-9X2Q',
        userId: customer._id,
        customer: {
          fullName: 'Rahul Sharma',
          email: 'demo@example.com',
          phone: '+91 98765 43210',
        },
        items: [
          {
            id: 'pizza-1-default',
            foodItem: { name: 'Tandoori Paneer Tikka Pizza', price: 399, image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&q=80' },
            quantity: 1,
            selectedCustomizations: [
              { groupId: 'size', groupTitle: 'Size', optionId: 'medium', optionName: 'Medium (12")', price: 50 },
            ],
            selectedAddOns: [],
            unitPrice: 449,
            totalPrice: 449,
          },
          {
            id: 'dessert-1-default',
            foodItem: { name: 'Gulab Jamun', price: 129, image: '/images/gulab_jamun.jpg' },
            quantity: 1,
            selectedCustomizations: [],
            selectedAddOns: [],
            unitPrice: 129,
            totalPrice: 129,
          },
        ],
        subtotal: 578,
        deliveryFee: 49,
        tax: 46,
        discount: 50,
        grandTotal: 623,
        status: 'Delivered',
        deliveryAddress: {
          fullName: 'Rahul Sharma',
          phone: '+91 98765 43210',
          email: 'demo@example.com',
          houseNumber: 'Flat 402, Sunshine Apts',
          street: '12th Main, Indiranagar',
          city: 'Bangalore',
          state: 'Karnataka',
          pincode: '560038',
        },
        deliveryType: 'standard',
        paymentMethod: 'card',
        paymentStatus: 'Paid',
        estimatedDeliveryTime: 'Delivered',
        statusTimestamps: {
          placed: new Date(Date.now() - 24 * 60 * 60 * 1000),
          confirmed: new Date(Date.now() - (24 * 60 - 5) * 60 * 1000),
          preparing: new Date(Date.now() - (24 * 60 - 10) * 60 * 1000),
          outForDelivery: new Date(Date.now() - (24 * 60 - 25) * 60 * 1000),
          delivered: new Date(Date.now() - (24 * 60 - 45) * 60 * 1000),
        },
      },
    ];

    await Order.insertMany(sampleOrders);
    console.log(`📦 ${sampleOrders.length} sample orders created`);

    console.log('\n✅ Database seeded successfully!');
    console.log('\n📋 Login Credentials:');
    console.log('   Admin: admin@foodiehaven.com / admin123');
    console.log('   Customer: demo@example.com / demo123\n');

    process.exit(0);
  } catch (error: any) {
    console.error('❌ Error seeding database:', error.message);
    process.exit(1);
  }
};

seedData();
